# This file contains patches described in the GNU Emacs documentation,
# and may be redistributed and/or modified under the terms of the GNU
# General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
name: Build Emacs with selinux
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-version: [33]
        # ndk-version: [23.2.8568313, 24.0.8215888, 25.2.9519653]
        ndk-version: [25.2.9519653]
        # abi: [i686, x86_64, aarch64, armv7a, mips64, mips, arm]
        abi: [aarch64]
        # minsdk: [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
        minsdk: [24]
    steps:
      # Setup java/jdk.
    - name: Setup java environment
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
      #
      # Setup android environment.
    - name: Setup android
      uses: android-actions/setup-android@v2
      #
      # Checkout source.
    - name: Checkout source
      uses: actions/checkout@v3
    #
    # Get core(libpackagelistparser) and build it
    - name: get libpackagelistparser and build it
      run: |
        git clone https://android.googlesource.com/platform/system/core
        git -C core checkout nougat-release
        $ANDROID_HOME/ndk/${{ matrix.ndk-version }}/ndk-build \
          -C core \
          NDK_PROJECT_PATH=./ \
          APP_BUILD_SCRIPT=./Android.mk \
          NDK_DEBUG=1 \
          V=1
        find core -type f
    #
    # Get libpcre and build it
    - name: get libpcre and build it
      run: |
        git clone https://android.googlesource.com/platform/external/pcre
        git -C pcre checkout nougat-release
        $ANDROID_HOME/ndk/${{ matrix.ndk-version }}/ndk-build \
          -C pcre \
          NDK_PROJECT_PATH=./ \
          APP_BUILD_SCRIPT=./Android.mk \
          APP_PLATFORM=android-24 \
          NDK_DEBUG=1 \
          V=1
        find pcre -type f
    #
    # Get libcrypto and build it
    - name: get libcrypto and build it
      run: |
        git clone https://android.googlesource.com/platform/external/boringssl
        git -C boringssl checkout nougat-release
        $ANDROID_HOME/ndk/${{ matrix.ndk-version }}/ndk-build \
          -C boringssl \
          NDK_PROJECT_PATH=./ \
          APP_BUILD_SCRIPT=./Android.mk \
          NDK_DEBUG=1 \
          V=1
        find boringssl -type f
