name: Check under ANDROID_HOME

on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: tree -d
      run: tree -d $ANDROID_HOME
    - name: find android.jar
      run: find $ANDROID_HOME -type f -name android.jar
    
