name: Build and deploy htagged pages some branches.
on:
  workflow_dispatch:
#
jobs:
  htags:
    name: Create htags pages.
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Setup environment.
      - name: Install GNU global, etc.
        run: |
          git config --global user.email "ayanokoji.takesi@gmail.com"
          git config --global user.name "ayatakesi"
          sudo apt-get -y install global
      # Checkout source for htag-ing.
      - name: Checkout source.
        run: |
          git clone https://github.com/emacs-mirror/emacs
      # Checkout repository for distributing tagged pages.
      - name: Checkout pages.
        run: |
          git clone https://github.com/ayatakesi/ayatakesi.github.io
          rm -fr ayatakesi.github.io/src/*
      # master
      - name: Generate and deploy pages to ayatakesi.github.io.
        run: |
          git -C emacs checkout master
          mkdir -p ayatakesi.github.io/src/emacs/master
          htags -C emacs --gtags --line-number=6 ../ayatakesi.github.io/src/emacs/master
          git -C emacs reset --hard
      # emacs-29
      - name: Generate and deploy pages to ayatakesi.github.io.
        run: |
          git -C emacs checkout emacs-29
          mkdir -p ayatakesi.github.io/src/emacs/emacs-29
          htags -C emacs --gtags --line-number=6 ../ayatakesi.github.io/src/emacs/emacs-29
          git -C emacs reset --hard
      # feature/android
      - name: Generate and deploy pages to ayatakesi.github.io.
        run: |
          git -C emacs checkout feature/android
          mkdir -p ayatakesi.github.io/src/emacs/feature/android
          htags -C emacs --gtags --line-number=6 ../ayatakesi.github.io/src/emacs/feature/android
          git -C emacs reset --hard
      - name: Commit and push pages.
        run: |
          git -C ayatakesi.github.io add src
          git -C ayatakesi.github.io commit -m "Update src/*"
          git -C ayatakesi.github.io push https://${GITHUB_TOKEN}@github.com/ayatakesi/ayatakesi.github.io.git;
